<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="SchemaEvolution">
  <eClassifiers xsi:type="ecore:EClass" name="NewColumn">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tab" upperBound="-1" eType="#//Table"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" upperBound="-1"
        eType="#//Column"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Table">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cols" lowerBound="1" upperBound="-1"
        eType="#//Column" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NewTableName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Column">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tab" lowerBound="1" eType="#//Table"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameAttribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameEntity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveColumn">
    <eStructuralFeatures xsi:type="ecore:EReference" name="col" upperBound="-1" eType="#//Column"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddPk">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tab" upperBound="-1" eType="#//Table"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NewTable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tab" lowerBound="1" eType="#//Table"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prevTable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SplitColumn">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="table" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oldColumn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newColumns" lowerBound="1"
        upperBound="-1" eType="#//Column"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="criteria" lowerBound="1"
        upperBound="-1" eType="#//CriteriaSplit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MergeTable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tableSource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tableTarget" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newTableName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CopyTable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tableSource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="copiedTable" eType="#//Table"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SplitTable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tableSource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultingTables" lowerBound="1"
        upperBound="-1" eType="#//Table"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MergeColumn">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetColumn" lowerBound="1"
        eType="#//Column"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceColumns" lowerBound="2"
        upperBound="-1" eType="#//Column"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="table" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemovePK">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="table" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="previous" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnRemoved" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveTable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="remove" eType="#//Table"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CriteriaSplit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="column" eType="#//Column"/>
  </eClassifiers>
</ecore:EPackage>
