TRUNCATE "testCustomV8JoinColumn".table1;
Insert into "testCustomV8JoinColumn".table1 (idauthor, idbook, title, subtitle) values ('1', '2', 'lotr', 'rotk');
Insert into "testCustomV8JoinColumn".table1 (idauthor, idbook, title, subtitle) values ('3', '4', 'asoiaf', 'winds of winter');
Insert into "testCustomV8JoinColumn".table1 (idauthor, idbook, title, subtitle) values ('5', '6', 'frieren', 'exam arc');