TRUNCATE "testWireV8NewTableMigrationFromPreviousVersion".scim_user;
TRUNCATE "testWireV8NewTableMigrationFromPreviousVersion".scim_user_times;
Insert into "testWireV8NewTableMigrationFromPreviousVersion".scim_user (id) values ('1');
Insert into "testWireV8NewTableMigrationFromPreviousVersion".scim_user (id) values ('2');
Insert into "testWireV8NewTableMigrationFromPreviousVersion".scim_user (id) values ('3');