name: test-all
on:
  push:
    branches-ignore:
      - 'dependabot/**' #avoid duplicates: only run the PR, not the commit
      - 'gh-pages' #github pages do not trigger all tests
    tags-ignore:
      - 'v*' #avoid rerun existing commit on release
  pull_request:
    branches:
      - 'main'
env:
  TEST_CASSANDRA_PWD: ${RANDOM}${RANDOM}${RANDOM}
jobs:
  test-java:
    runs-on: ubuntu-latest
    #if: ${{ false }}  # disable for now
    #avoids duplicate execution of pr from local repo, but allows pr from forked repos and dependabot
    if: (github.event_name != 'pull_request' && ! github.event.pull_request.head.repo.fork) || (github.event_name == 'pull_request' && (github.event.pull_request.head.repo.fork || startsWith(github.head_ref, 'dependabot/')))
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      # Starts the DBMS containers when applicable
      - name: Launch Cassandra
        run: |
          docker run --name test-cassandra -d -p 9042:9042 cassandra:3.11  --restart unless-stopped \
            cassandra:3.11
          sleep 30
          docker logs test-cassandra
          docker exec test-cassandra cqlsh localhost 9042 -e "CREATE ROLE testcassandra WITH PASSWORD = '$TEST_CASSANDRA_PWD' AND LOGIN = true;"
          docker exec test-cassandra cqlsh localhost 9042 -e "GRANT ALL PERMISSIONS on ALL KEYSPACES to testcassandra;"
      
      - name: Modify modevo.properties
        run: |
          sed -i 's/usercassandra/testcassandra/' ${GITHUB_WORKSPACE}/modevo.properties
          sed -i 's/passwordcassandra/$TEST_CASSANDRA_PWD/' ${GITHUB_WORKSPACE}/modevo.properties

      - name: Test and aggregate surefire report
        run: mvn test surefire-report:report -Daggregate=true -Dmaven.test.failure.ignore=true -U --no-transfer-progress

      - name: Additional aggregated junit report
        uses: javiertuya/junit-report-action@v1
        with:
          surefire-files: "**/target/surefire-reports/TEST-*.xml"
          report-dir: target/site

      - name: Generate report checks
        if: always()
        uses: mikepenz/action-junit-report@v4.2.1
        with:
          check_name: "test-result"
          report_paths: "**/surefire-reports/TEST-*.xml"
          fail_on_failure: 'true'

      - if: always()
        name: Publish test report files
        uses: actions/upload-artifact@v4
        with:
          name: "test-report-files"
          path: |
            target/site
            **/target/site/jacoco/jacoco.xml
            **/target/surefire-reports

  sonarqube:
    needs: [test-java]
    #if: ${{ false }}  # disable for now
    #This job fails when comming from a dependabot PR (can't read the sonarqube token for security reasons).
    #Links to discussions and workaround at: https://github.com/giis-uniovi/samples-giis-template/issues/4
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: javiertuya/sonarqube-action@v1.3.1
        with: 
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          restore-artifact-name1: "test-report-files"

  publish-java-snapshot:
    if: ${{ false }}  # disable for now
    #avoid publishing PRs and dependabot branches
    #if: ${{ github.event_name != 'pull_request' && !startsWith(github.ref, 'refs/heads/dependabot/') && !startsWith(github.ref, 'refs/heads/dashgit/combined/') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: javiertuya/branch-snapshots-action@v1.2.2
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          java-version: '17'
          mvn-deploy-args: '-P publish-github -DskipTests=true -Dmaven.test.failure.ignore=false -U --no-transfer-progress'
          delete-old-snapshots: true
          min-snapshots-to-keep: 2
          always-keep-regex: "\\d*\\.\\d*\\.\\d*-main-SNAPSHOT$"
